---
:backgroundrb:
  :ip: "127.0.0.1"
  :port: "11008"
  :environment: "development"

:schedules:
  :captive_portal_worker:
    :captive_portals_upkeep:
      :trigger_args: 0  *  * * * * *
  :house_keeper_worker:
    :remove_stale_sessions:
      :trigger_args: 0  0  2 * * 0 *
    :remove_stale_bdrbs:
      :trigger_args: 0  30 2 * * 0 *
